[package]
name = "rust-ledger"
version = "0.1.0"
authors = ["ebcrowder <ebcrowder@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
description = "CLI accounting tool"
repository = "https://github.com/ebcrowder/rust-ledger"
readme = "README.md"

[dependencies]
serde_yaml = "0.8.11"
serde = "1.0.101"
csv = "1.1.1"
num-format = "0.4.0"

[dev-dependencies]
assert_cmd = "0.11.1"
predicates = "1.0.1"
tempfile = "3.1.0"
