[package]
name = "rust_ledger"
version = "0.1.5"
authors = ["ebcrowder <ebcrowder@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
description = "CLI accounting tool"
repository = "https://github.com/ebcrowder/rust_ledger"
readme = "README.md"

[dependencies]
serde_yaml = "0.8.11"
serde = { version = "1.0.104", features = ["derive"] } 
csv = "1.1.1"
num-format = "0.4.0"

[dev-dependencies]
assert_cmd = "0.12.0"
predicates = "1.0.2"
tempfile = "3.1.0"
